### ISSUE TITLE
Heading 1 

### ISSUE THREAD

**Issue by melissamcewen** [tyeshi777/prj-rev-bwfs-dasmoto#3]
For the heading, here are the things you should apply to the h1 to get it to match spec

```css
h1 {
  background-image: 
  text-align: ;
  font-size: ;
  color: ;
}

```

You have some of them, but some of the other properties are causing it to not be the right size
